version: 2

sphinx:
  configuration: doc/conf.py

formats: all

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libeigen3-dev

python:
  install:
    - requirements: doc/requirements-rtd.txt
